[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cycleback = "7o67cgqG8dZRBEw8zqb8m6aG2FHRpQShTTskGGs59FrU"
oracle = "CarbN2rxkvGLJQECuKJ4y931xCGwbmL3Bbmi7W8KFjmT"

[programs.devnet]
cycleback = "7o67cgqG8dZRBEw8zqb8m6aG2FHRpQShTTskGGs59FrU"
oracle = "CarbN2rxkvGLJQECuKJ4y931xCGwbmL3Bbmi7W8KFjmT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
